[package]
name = "chrishayuk/hello-wasi-assemblyscript"
version = "0.0.2"
description = "hello world from chrishayuk"
readme = "README.md"
repository = "https://github.com/chrishayuk/hello-wasi-assemblyscript"
license = "MIT"

[[module]]
name = "hello-wasi-assemblyscript"
source = "build/release.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "hello-wasi-assemblyscript"
module = "hello-wasi-assemblyscript"
